name: apply

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.29
      - name: Create tfvars
        run: echo "${{ secrets.TFVARS }}" > terraform/github/vars.tfvars
      - name: Terraform Format
        run: make format
      - name: Terraform init
        run: make remote-enable
      - name: Terraform apply
        run: make apply
      - name: Setup git
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config --local user.name GitHubActions
          git config --local user.email githubactions@example.com
          git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      - name: Save tfstate
        run: |
          git add -A
          DIFF=`git diff --cached --numstat | wc -l`
          if [ $DIFF -eq 0 ]; then
            exit 0
          fi
          git commit -am 'GitHub Actions commit' --allow-empty
          git push origin main